---
title: Intro to GLMs
author: Will Gertsch
date: '2020-07-21'
slug: intro-to-glms
categories: []
tags:
  - glm
  - regression
  - model
description: ''
keywords: []
math: no
---

I took a course in generalized linear models in my first year of graduate school, but I was never happy with the organization of the material in our lecture slides or in the books I have read on the subject. I feel that introducing the general theory as early as possible is helpful in understanding the many, many models that come up in a a course on GLMs. Therefore, I am making a mini-course that follows this philosophy.

This is going to be a series of posts and I am expecting the outline to be something like this:

1. Logistic regression

2. General GLM theory

3. Inference

4. Model fitting

5. An overview of the specific details for popular GLMs.

My favorite books (the ones I'll be referencing) on GLMs are:

- "Extending the Linear Model with R" by Faraway
- "An Introduction to Generalized Linear Models" by Dobson
- Wikipedia (no really, the GLM article is great)

